import React from "react";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import { ThemeProvider } from "next-themes";

import "./globals.css";
import { TRPCProvider } from "@/providers/trpc-provider";
import ThemeProviders from "@/providers/theme-providers";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.variable} font-poppins antialiased`}
      >
          <TRPCProvider>
            <ThemeProviders>
              {children}
            </ThemeProviders>
          </TRPCProvider>
      </body>
    </html>
  );
}
